### ISSUE TITLE
Hover/focus states misaligned in default theme navigation menu

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7077]
**Describe the bug**
When hovering over a navigation menu item in the default theme, the dropdown menu is shifted right slightly. This is corrected when clicking on the parent menu item, which causes the focus to be set. The dropdown menu shifts left again.

**To Reproduce**
1. Create a navigation menu with at least one dropdown menu.
2. Move mouse over the nav menu item to show the dropdown menu.
3. Click on parent nav menu item and see the dropdown menu shift left.

**What application are you using?**
3.3.0-6

**Additional information**
The original [report in the forum](https://forum.pkp.sfu.ca/t/ojs-3-3-0-6-visual-issue-with-a-drop-down-menu-in-manuscript-theme/67747) contains screenshots illustrating the problem in the Manuscript theme, but the same problem exists in the default theme.

**Comment by NateWr** [comment]
This problem arises because the Popper.js library, which we use to handle the dropdowns on click, automatically adjusts the position of the dropdown based on the screen position. There were some slight discrepancies between this automatic positioning and the CSS-based hover positions.

The following PRs reduce the frequency of jank. However, because Popper.js will shift a dropdown away from the edge of the screen, there are still some cases where there the position may shift between hover/focus states. I don't think we can fix unless we switch libraries or abandon hover states.

Because this change could negatively impact some child themes, I've only provided PRs for the `main` branch.

PRs:
https://github.com/pkp/ojs/pull/3139
https://github.com/pkp/omp/pull/976
https://github.com/pkp/ops/pull/156

A fix for the Manuscript theme can be found at https://github.com/NateWr/defaultManuscript/commit/638e95c56e81d83ced234daceb61502ae12ffe8a.

**Comment by crosfield** [comment]
I see, ok, thanks @NateWr!

**Comment by mpbraendle** [comment]
Hmm. No, it is not really fixed. If you hover over a submenu item of the first dropdown menu, the position bar is outside the menu box. See attached screenshot.

<img width="1337" alt="first_menu_bar_outside" src="https://user-images.githubusercontent.com/5315105/155537942-59ffaec1-0f80-4a7f-8e1d-1cac271f88f3.png">

This only happens for a dropdown menu that is on the first position of the primary menu bar.

The problem seems to be connected to line 348 of the less code.

**Comment by voffch** [comment]
> This only happens for a dropdown menu that is on the first position of the primary menu bar.

That's because the dropdown for first item is (for some reason) shifted left by popper.js. I've seemingly managed to fix this in my child theme for OJS 3.3 with the following hack (the first rule is basically the [original fix](https://github.com/pkp/ojs/pull/3139), but note -7px in the second rule):

```css
#navigationPrimary .dropdown-menu {
  position: absolute;
  transform: translate3d(7px, 40px, 0px);
  top: 0px;
  left: 0px;
  will-change: transform;
}

#navigationPrimary > li:first-child .dropdown-menu {
  transform: translate3d(-7px, 40px, 0px);
}
```

Now the dropdowns are visually under the menu items, and they don't jump around as they used to when the menu is clicked.

There is still a slight issue with the horizontal position of the border-left in the first dropdown menu. If this irritates you, you can try replacing the second rule with these two

```css
#navigationPrimary > li:first-child .dropdown-menu {
  transform: translate3d(0px, 40px, 0px);
}

#navigationPrimary > li:first-child a {
  margin-left: 0;
}
```

to see if this misalignment looks better than the previous one.

The ID selectors are for additional rule specificity (I hate !important).
